### ISSUE TITLE
Why didn't VCSs make the list?

### ISSUE THREAD

**Issue by j3mdamas** [jperkel/nature_code_survey#2]
Hi,

When I read the Nature article, I was surprised of not seeing version control systems (VCS) in the list, as they totally transformed the way software is produced. I mean, I am opening an issue on the most popular website of its kind supported by the most popular VCS, Git.

So I actually followed the link in the article to this repository, and when I opened the file: https://github.com/jperkel/nature_code_survey/blob/main/free_responses.txt and did a quick search, there are 18 entries for "git".

Is it possible is was overlooked? I also didn't do any further analysis other than a plain "Ctrl+F".

**Comment by josejimenezluna** [comment]
Agreeing with @j3mdamas here. Having jupyter notebooks on the list while ignoring VCS is quite disheartening.

**Comment by jperkel** [comment]
Thank you for your feedback, @j3mdamas @josejimenezluna. The survey was done after the article was published -- we asked readers which other tools they thought we should have included.

**Comment by j3mdamas** [comment]
Thanks for the very quick answer, @jperkel, and for clarifying about the "other tools" survey.

I think there are two separate issues. One is the fact that community (i.e. "the readers" in Figure titled "Top choices for Science Code") have put very little importance to VCSs in relation to other recent contributions, which is rather subjective, but quite appaling as José mentions.

But my initial comment was more related to the data that you made available. If the data in https://github.com/jperkel/nature_code_survey/blob/main/free_responses.txt was used to produce the Figure titled "Overlooked Software", I think that figure should be revisited, as "git" (mostly GitHub) was mentioned 18 times on the raw data, which puts it above Google, Lisp, HTML and Pascal. But perhaps this is not the right forum. Please let me know what would be the best way for me to suggest a correction.

Thanks!
